/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CookieFooter {
        "name": string;
        "title": string;
        "url": string;
    }
}
declare global {
    interface HTMLCookieFooterElement extends Components.CookieFooter, HTMLStencilElement {
    }
    var HTMLCookieFooterElement: {
        prototype: HTMLCookieFooterElement;
        new (): HTMLCookieFooterElement;
    };
    interface HTMLElementTagNameMap {
        "cookie-footer": HTMLCookieFooterElement;
    }
}
declare namespace LocalJSX {
    interface CookieFooter {
        "name"?: string;
        "title"?: string;
        "url"?: string;
    }
    interface IntrinsicElements {
        "cookie-footer": CookieFooter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cookie-footer": LocalJSX.CookieFooter & JSXBase.HTMLAttributes<HTMLCookieFooterElement>;
        }
    }
}
